import { useEffect, useState } from 'react';
import { Alert, Avatar, Box, Button, Card, CardContent, Chip, CircularProgress, Container, Drawer, List, ListItemButton, ListItemIcon, ListItemText, Paper, Snackbar, Stack, TextField, Toolbar, Typography } from '@mui/material';
import DashboardRoundedIcon from '@mui/icons-material/DashboardRounded';
import EventRoundedIcon from '@mui/icons-material/EventRounded';
import MedicationRoundedIcon from '@mui/icons-material/MedicationRounded';
import PeopleAltRoundedIcon from '@mui/icons-material/PeopleAltRounded';
import LocalHospitalRoundedIcon from '@mui/icons-material/LocalHospitalRounded';
import LogoutRoundedIcon from '@mui/icons-material/LogoutRounded';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import { appointmentsApi, authApi, demoData, patientsApi, prescriptionsApi } from './api';
import './App.css';
import './portal.css';

const green = '#116b59';
const nav = [['Overview', DashboardRoundedIcon], ['Patients', PeopleAltRoundedIcon], ['Appointments', EventRoundedIcon], ['Prescriptions', MedicationRoundedIcon]];

function Login({ onLogin }) {
  const [form, setForm] = useState({ email: '', password: '' });
  const [error, setError] = useState('');
  const submit = async (event) => { event.preventDefault(); try { const result = await authApi.login(form); localStorage.setItem('careflow_token', result.token); onLogin(result.user); } catch (requestError) { setError(requestError.response?.data?.error || 'Unable to sign in.'); } };
  const demo = () => { localStorage.setItem('careflow_demo', 'true'); onLogin({ name: 'Alex Morgan', role: 'doctor' }); };
  return <Box className="login-screen"><Paper className="login-card"><Avatar sx={{ bgcolor: green, mb: 2 }}><LocalHospitalRoundedIcon /></Avatar><Typography variant="overline">CAREFLOW HEALTH</Typography><Typography variant="h4" fontWeight={800}>Welcome back</Typography><Typography color="text.secondary" mb={3}>Sign in to your clinical workspace.</Typography><Box component="form" onSubmit={submit} display="grid" gap={2}><TextField required label="Work email" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><TextField required label="Password" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} />{error && <Alert severity="error">{error}</Alert>}<Button type="submit" variant="contained">Sign in</Button><Button onClick={demo}>Explore demo workspace</Button></Box></Paper></Box>;
}

function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('careflow_user') || 'null'));
  const [tab, setTab] = useState(0); const [data, setData] = useState({ patients: [], appointments: [], prescriptions: [] }); const [busy, setBusy] = useState(true); const [notice, setNotice] = useState('');
  const load = async () => { setBusy(true); try { const [patients, appointments, prescriptions] = await Promise.all([patientsApi.list(), appointmentsApi.list(), prescriptionsApi.list()]); setData({ patients, appointments, prescriptions }); } catch (error) { if (localStorage.getItem('careflow_demo')) setData(demoData); else setNotice(error.response?.data?.error || 'Could not load workspace data.'); } finally { setBusy(false); } };
  useEffect(() => { if (user) { localStorage.setItem('careflow_user', JSON.stringify(user)); load(); } }, [user]);
  const act = async (request, message) => { try { await request(); await load(); setNotice(message); } catch (error) { setNotice(error.response?.data?.error || 'The request could not be completed.'); } };
  if (!user) return <Login onLogin={setUser} />;
  const logout = () => { ['careflow_token', 'careflow_user', 'careflow_demo'].forEach((key) => localStorage.removeItem(key)); setUser(null); };
  const titles = ['Overview', 'Patients', 'Appointments', 'Prescriptions'];
  const renderContent = () => { if (busy) return <Box className="loading"><CircularProgress /><Typography color="text.secondary">Loading care workspace...</Typography></Box>; if (tab === 1) return <Records title="Patients" subtitle="Manage demographics and care notes." items={data.patients} empty="No patients yet." actionLabel="Add patient" fields={['name', 'email', 'phone']} onSave={(value) => act(() => patientsApi.create(value), 'Patient saved')} onDelete={(id) => act(() => patientsApi.remove(id), 'Patient deleted')} />; if (tab === 2) return <Records title="Appointments" subtitle="Schedule and coordinate upcoming care." items={data.appointments} empty="No appointments yet." actionLabel="Schedule visit" fields={['patientId', 'doctorId', 'startsAt', 'endsAt', 'reason']} onSave={(value) => act(() => appointmentsApi.create(value), 'Appointment scheduled')} onDelete={(id) => act(() => appointmentsApi.cancel(id), 'Appointment cancelled')} />; if (tab === 3) return <Records title="Prescriptions" subtitle="Review medication plans and treatment status." items={data.prescriptions} empty="No prescriptions yet." onDelete={(id) => act(() => prescriptionsApi.complete(id), 'Prescription completed')} />; return <><Header title={`Good morning, ${user.name?.split(' ')[0] || 'there'}.`} subtitle="Here is your care operations overview for today." /><Box className="stats-grid">{[['Patients', data.patients.length, '#2d9b78'], ['Upcoming visits', data.appointments.filter((i) => i.status === 'scheduled').length, '#3d83c6'], ['Active prescriptions', data.prescriptions.filter((i) => i.status === 'active').length, '#d98a42']].map(([label, value, color]) => <Card key={label} sx={{ borderTop: `4px solid ${color}` }}><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h3" fontWeight={800}>{value}</Typography></CardContent></Card>)}</Box><Paper sx={{ mt: 3, p: 3 }}><Typography variant="h6" fontWeight={800}>Care activity</Typography><Typography color="text.secondary">Connected to patient, appointment, and prescription services.</Typography><Stack direction="row" gap={1} mt={2}><Chip label={`Role: ${user.role}`} color="success" /><Chip label="JWT secured" variant="outlined" /></Stack></Paper></>; };
  return <Box className="portal"><Drawer variant="permanent" className="drawer"><Toolbar className="brand"><Avatar sx={{ bgcolor: '#dcefe8', color: green }}><LocalHospitalRoundedIcon /></Avatar><Typography fontWeight={900} color={green}>Careflow</Typography></Toolbar><Typography className="workspace-label">CLINICAL WORKSPACE</Typography><List>{nav.map(([label, Icon], index) => <ListItemButton key={label} selected={tab === index} onClick={() => setTab(index)}><ListItemIcon><Icon /></ListItemIcon><ListItemText primary={label} /></ListItemButton>)}</List><Box mt="auto" p={2}><ListItemButton onClick={logout}><ListItemIcon><LogoutRoundedIcon /></ListItemIcon><ListItemText primary="Sign out" /></ListItemButton></Box></Drawer><Box component="main" flex={1}><Toolbar className="topbar"><Typography color="text.secondary">Workspace / {titles[tab]}</Typography><Box flex={1} /><Avatar sx={{ bgcolor: '#d49777' }}>{user.name?.slice(0, 2).toUpperCase()}</Avatar></Toolbar><Container maxWidth="lg" className="content">{renderContent()}</Container></Box><Snackbar open={Boolean(notice)} autoHideDuration={3500} onClose={() => setNotice('')}><Alert severity="info">{notice}</Alert></Snackbar></Box>;
}

function Header({ title, subtitle }) { return <Box mb={3}><Typography variant="h4" fontWeight={800}>{title}</Typography><Typography color="text.secondary">{subtitle}</Typography></Box>; }
function Records({ title, subtitle, items, empty, actionLabel, fields = [], onSave, onDelete }) { const [form, setForm] = useState({}); const [open, setOpen] = useState(false); return <><Header title={title} subtitle={subtitle} /><Button startIcon={<AddRoundedIcon />} variant="contained" onClick={() => setOpen(true)} sx={{ mb: 2 }}>{actionLabel}</Button><Stack gap={1.5}>{items.length === 0 && <Typography color="text.secondary">{empty}</Typography>}{items.map((item) => <Card key={item._id || item.id}><CardContent className="record-row"><Box flex={1}><Typography fontWeight={700}>{item.name || item.reason || item.diagnosis || 'Medication plan'}</Typography><Typography variant="body2" color="text.secondary">{item.email || item.status || item.patientId || item.medicines?.map((m) => m.name).join(', ')}</Typography></Box><Chip label={item.status || 'Active'} color={item.status === 'cancelled' || item.status === 'completed' ? 'default' : 'success'} /><Button color="error" onClick={() => onDelete(item._id || item.id)}>{title === 'Prescriptions' ? 'Complete' : title === 'Appointments' ? 'Cancel' : 'Delete'}</Button></CardContent></Card>)}</Stack><Paper component="form" onSubmit={(event) => { event.preventDefault(); setOpen(false); onSave(form); }} sx={{ display: open ? 'grid' : 'none', gap: 2, p: 3, mt: 3 }}>{fields.map((field) => <TextField key={field} label={field} required={['name', 'email', 'patientId', 'doctorId', 'startsAt', 'endsAt'].includes(field)} type={field.includes('At') ? 'datetime-local' : 'text'} InputLabelProps={field.includes('At') ? { shrink: true } : undefined} onChange={(e) => setForm({ ...form, [field]: e.target.value })} />)}<Button type="submit" variant="contained">Save</Button></Paper></>; }

export default App;
